[env]
TERM = "xterm-256color"

[window]
opacity = 0.95

## DARK COLOR SCHEME
# [colors.primary]
# # background = "#574464" # a dark purple-y/plum-y background
# foreground = "#e3c7fc"
#
# [colors.cursor]
# text = "#09090d"
# cursor = "#f1c4e0"
#
# [colors.vi_mode_cursor]
# text = "#f1c4e0"
# cursor = "#edeff0"
#
# [colors.search.matches]
# foreground = "#09090d"
# background = "#f1c4e0"
#
# [colors.search.focused_match]
# foreground = "#09090d"
# background = "#262440"
#
# [colors.footer_bar]
# foreground = "#09090d"
# background = "#f1c4e0"
#
# [colors.hints.start]
# foreground = "#09090d"
# background = "#8897F4"
#
# [colors.hints.end]
# foreground = "#09090d"
# background = "#f1c4e0"
#
# [colors.selection]
# text = "#09090d"
# background = "#f1c4e0"
#
# [colors.normal]
# black = "#140a1d"
# red = "#FF4971"
# green = "#8897F4"
# yellow = "#B52A5B"
# blue = "#bd93f9"
# magenta = "#E9729D"
# cyan = "#F18FB0"
# white = "#f1c4e0"
#
# [colors.bright]
# black = "#a8899c"
# red = "#FF4971"
# green = "#8897F4"
# yellow = "#B52A5B"
# blue = "#bd93f9"
# magenta = "#E9729D"
# cyan = "#F18FB0"
# white = "#f1c4e0"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"

[colors.primary]
background = '#525253'
foreground = '#f2f4f8'

[colors.normal]
black = "#282828"
red = "#ee5396"
magenta = "#25be6a"
yellow = "#08bdba"
blue = "#78a9ff"
green = "#be95ff"
cyan = "#33b1ff"
white = "#dfdfe0"

[colors.bright]
black = "#484848"
red = "#f16da6"
magenta = "#46c880"
yellow = "#2dc7c4"
blue = "#8cb6ff"
green = "#c8a5ff"
cyan = "#52bdff"
white = "#e4e4e5"

## LIGHT THEME
# Colors (Ayu Light)

# Default colors - taken from ayu-colors
#[colors.primary]
#background = '#FCFCFC'
#foreground = '#5C6166'

# Normal colors - taken from ayu-iTerm
#[colors.normal]
#black   = '#010101'
#red     = '#e7666a'
#green   = '#80ab24'
#yellow  = '#eba54d'
#blue    = '#4196df'
#magenta = '#9870c3'
#cyan    = '#51b891'
#white   = '#c1c1c1'

# Bright colors - pastel lighten 0.1 <normal> except black lighten with 0.2
#[colors.bright]
#black   = '#343434'
#red     = '#ee9295'
#green   = '#9fd32f'
#yellow  = '#f0bc7b'
#blue    = '#6daee6'
#magenta = '#b294d2'
#cyan    = '#75c7a8'
#white   = '#dbdbdb'

## OTHER COLORS
# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"
#
# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"
#
# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"
#
# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"
#
# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"
#
# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"
#
# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"
