[env]
TERM = "xterm-256color"

[window]
opacity = 0.86
decorations = "None"

[colors.primary]
background = '#525253'
foreground = '#f2f4f8'

[colors.normal]
black = "#282828"
red = "#ee5396"
magenta = "#25be6a"
yellow = "#08bdba"
blue = "#78a9ff"
green = "#be95ff"
cyan = "#33b1ff"
white = "#dfdfe0"

[colors.bright]
black = "#484848"
red = "#f16da6"
magenta = "#46c880"
yellow = "#2dc7c4"
blue = "#8cb6ff"
green = "#c8a5ff"
cyan = "#52bdff"
white = "#e4e4e5"

[colors.dim]
black = "#9893a5"
red = "#b4637a"
green = "#286983"
yellow = "#ea9d34"
blue = "#56949f"
magenta = "#907aa9"
cyan = "#d7827e"
white = "#575279"
